# Generated by Django 3.0.2 on 2020-01-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200128_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ox',
                'verbose_name_plural': 'oxen',
            },
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['rating'], 'verbose_name': 'the website', 'verbose_name_plural': 'the websites'},
        ),
        migrations.AlterModelTable(
            name='website',
            table='website_custom_table_name',
        ),
    ]
